### PR TITLE
fixed youtube-dl library issue | download working

### PR DESCRIPTION
**Pull request by EmmanuelDav**
Fixed download issue by adding a youtube-dl library and removing the modules

### CODE REVIEW

**Comment by abdellatif-laghjaj** [comment]
Nice dude,
can u please provide me with some screenshots of the when its downloading, before i test it and confirm the PR

**Comment by abdellatif-laghjaj** [comment]
I test it, and its not working
image

**Comment by EmmanuelDav** [comment]
It works with a TikTok link, just tested YouTube and it wasn't working, I will fix it

**Comment by abdellatif-laghjaj** [comment]
Okay try to fix download aslo for other platforms, i mean facebook, instagram...
because i tried to fix it but nothing work for me

**Comment by EmmanuelDav** [comment]
it's working now, it takes time to download because it chooses the best quality with the highest MB

**Comment by EmmanuelDav** [comment]
Screenshot_20231009-023821
Screenshot_20231009-023630

**Comment by EmmanuelDav** [comment]
I think you need to update the app to the latest youtube-dl library for it to work, the recent changes I made force the youtube-dl library to be implemented once the app launches. 

let me know if it still doesn't work

**Comment by abdellatif-laghjaj** [comment]
Good my friend it works, if that the case, i want u to:

- **Add the update method in the startup of the app!, so user don't have to update it manulay**
- **Try to generate bundle apk and u can see some errors, witch it was'nt before**
- **If u succesed to fix the issue and the apk generated, check if the size of the apk, if it's big, i dont know if you can find a way to make it small, cuz i try hard with it but i did'nt find a way**

Those changes will be so apreciated

**Comment by EmmanuelDav** [comment]
Alright, I would look into it. Also, can you add hacktoberfest as a topic to this repo? I would be greatly appreciated

**Comment by EmmanuelDav** [comment]
Hey Friend, I don't think the file size can be reduced that's due to the files that come with the youtube-dl library, files like libpython.zip.so and libffmpeg.zip.so.  

Using apk-analyzer you will see that the library is occupying all the storage

**Comment by abdellatif-laghjaj** [comment]
Done my friend, i added the hacktobefest topic to the repo,
But for the apk it won't be generated for me:
image
image

**Comment by EmmanuelDav** [comment]
Done

**Comment by abdellatif-laghjaj** [comment]
Nice my friend you did a great job,
I'll merge your PR now
GG :)

**Pull request merged**
